"""
=============================================================
CodeAlpha Internship — Task 2: Exploratory Data Analysis (EDA)
=============================================================
Dataset : books_dataset.csv  (generated by Task 1)
          OR the built-in Titanic dataset (auto-downloaded)
Covers  : Shape, dtypes, missing values, statistics,
          correlation, outliers, distribution, hypothesis
=============================================================
Install dependencies:
    pip install pandas numpy matplotlib seaborn scipy
=============================================================
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import warnings
warnings.filterwarnings("ignore")

# ── 0. Load Dataset ───────────────────────────────────────
def load_data():
    """Load books CSV if present, otherwise use Titanic as demo."""
    try:
        df = pd.read_csv("books_dataset.csv")
        print("📂 Loaded: books_dataset.csv")
        return df, "books"
    except FileNotFoundError:
        url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
        df = pd.read_csv(url)
        print("📂 Loaded: Titanic dataset (demo)")
        return df, "titanic"


# ── 1. Basic Structure ────────────────────────────────────
def basic_info(df):
    print("\n" + "=" * 55)
    print("  STEP 1 — Dataset Structure")
    print("=" * 55)
    print(f"  Rows    : {df.shape[0]}")
    print(f"  Columns : {df.shape[1]}")
    print(f"\n  Column names & dtypes:\n{df.dtypes.to_string()}")
    print(f"\n  First 5 rows:\n{df.head().to_string()}")


# ── 2. Missing Value Analysis ─────────────────────────────
def missing_values(df):
    print("\n" + "=" * 55)
    print("  STEP 2 — Missing Value Analysis")
    print("=" * 55)
    missing = df.isnull().sum()
    pct = (missing / len(df) * 100).round(2)
    mv = pd.DataFrame({"Missing Count": missing, "Missing %": pct})
    mv = mv[mv["Missing Count"] > 0].sort_values("Missing %", ascending=False)

    if mv.empty:
        print("  ✅ No missing values found!")
    else:
        print(mv.to_string())

    # Visualise
    if not mv.empty:
        plt.figure(figsize=(8, 4))
        mv["Missing %"].plot(kind="bar", color="tomato", edgecolor="black")
        plt.title("Missing Values by Column (%)")
        plt.ylabel("Missing %")
        plt.tight_layout()
        plt.savefig("eda_missing_values.png", dpi=150)
        plt.close()
        print("\n  📊 Chart saved: eda_missing_values.png")

    return mv


# ── 3. Descriptive Statistics ─────────────────────────────
def descriptive_stats(df):
    print("\n" + "=" * 55)
    print("  STEP 3 — Descriptive Statistics (Numeric Columns)")
    print("=" * 55)
    numeric = df.select_dtypes(include=np.number)
    print(numeric.describe().round(2).to_string())

    # Skewness & Kurtosis
    print("\n  Skewness:")
    print(numeric.skew().round(3).to_string())
    print("\n  Kurtosis:")
    print(numeric.kurtosis().round(3).to_string())


# ── 4. Univariate Analysis ────────────────────────────────
def univariate_analysis(df):
    print("\n" + "=" * 55)
    print("  STEP 4 — Univariate Analysis")
    print("=" * 55)
    numeric_cols = df.select_dtypes(include=np.number).columns.tolist()

    fig, axes = plt.subplots(
        nrows=len(numeric_cols), ncols=2,
        figsize=(12, 4 * len(numeric_cols))
    )
    if len(numeric_cols) == 1:
        axes = [axes]

    for i, col in enumerate(numeric_cols):
        data = df[col].dropna()
        # Histogram
        axes[i][0].hist(data, bins=30, color="#4C72B0", edgecolor="white")
        axes[i][0].set_title(f"{col} — Distribution")
        axes[i][0].set_xlabel(col)
        axes[i][0].set_ylabel("Frequency")
        # Box plot
        axes[i][1].boxplot(data, vert=False, patch_artist=True,
                           boxprops=dict(facecolor="#55A868"))
        axes[i][1].set_title(f"{col} — Box Plot (Outliers)")
        axes[i][1].set_xlabel(col)

    plt.tight_layout()
    plt.savefig("eda_univariate.png", dpi=150)
    plt.close()
    print("  📊 Chart saved: eda_univariate.png")


# ── 5. Bivariate / Correlation Analysis ──────────────────
def correlation_analysis(df):
    print("\n" + "=" * 55)
    print("  STEP 5 — Correlation Analysis")
    print("=" * 55)
    numeric = df.select_dtypes(include=np.number)
    corr = numeric.corr()
    print(corr.round(2).to_string())

    plt.figure(figsize=(10, 7))
    mask = np.triu(np.ones_like(corr, dtype=bool))
    sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm",
                mask=mask, linewidths=0.5, square=True)
    plt.title("Correlation Heatmap")
    plt.tight_layout()
    plt.savefig("eda_correlation_heatmap.png", dpi=150)
    plt.close()
    print("  📊 Chart saved: eda_correlation_heatmap.png")


# ── 6. Outlier Detection (IQR method) ────────────────────
def detect_outliers(df):
    print("\n" + "=" * 55)
    print("  STEP 6 — Outlier Detection (IQR Method)")
    print("=" * 55)
    numeric = df.select_dtypes(include=np.number)
    for col in numeric.columns:
        Q1 = numeric[col].quantile(0.25)
        Q3 = numeric[col].quantile(0.75)
        IQR = Q3 - Q1
        lower, upper = Q1 - 1.5 * IQR, Q3 + 1.5 * IQR
        outliers = numeric[(numeric[col] < lower) | (numeric[col] > upper)]
        print(f"  {col:25s} — Outliers: {len(outliers)} "
              f"(range [{lower:.2f}, {upper:.2f}])")


# ── 7. Categorical Analysis ───────────────────────────────
def categorical_analysis(df):
    print("\n" + "=" * 55)
    print("  STEP 7 — Categorical Column Analysis")
    print("=" * 55)
    cat_cols = df.select_dtypes(include="object").columns.tolist()
    if not cat_cols:
        print("  No categorical columns found.")
        return

    for col in cat_cols[:3]:                # limit to first 3 for brevity
        vc = df[col].value_counts().head(10)
        print(f"\n  '{col}' — Top values:\n{vc.to_string()}")

    # Bar chart for first categorical column
    col = cat_cols[0]
    vc = df[col].value_counts().head(10)
    plt.figure(figsize=(9, 4))
    vc.plot(kind="bar", color=sns.color_palette("Set2", len(vc)), edgecolor="black")
    plt.title(f"Top 10 values — {col}")
    plt.ylabel("Count")
    plt.xticks(rotation=45, ha="right")
    plt.tight_layout()
    plt.savefig("eda_categorical.png", dpi=150)
    plt.close()
    print("\n  📊 Chart saved: eda_categorical.png")


# ── 8. Hypothesis Test (t-test example) ──────────────────
def hypothesis_test(df, dataset_type):
    print("\n" + "=" * 55)
    print("  STEP 8 — Hypothesis Testing")
    print("=" * 55)

    if dataset_type == "books":
        # H0: Mean price of 5-star books == mean price of 1-star books
        group_a = df[df["Rating (1-5)"] == 5]["Price (£)"].dropna()
        group_b = df[df["Rating (1-5)"] == 1]["Price (£)"].dropna()
        label = "Price: 5-star vs 1-star books"
    else:
        # Titanic — H0: Mean age of survivors == mean age of non-survivors
        group_a = df[df["Survived"] == 1]["Age"].dropna()
        group_b = df[df["Survived"] == 0]["Age"].dropna()
        label = "Age: Survivors vs Non-survivors"

    t_stat, p_value = stats.ttest_ind(group_a, group_b)
    print(f"\n  Test   : Independent samples t-test")
    print(f"  Groups : {label}")
    print(f"  H₀     : The two group means are equal")
    print(f"  t-stat : {t_stat:.4f}")
    print(f"  p-value: {p_value:.4f}")
    if p_value < 0.05:
        print("  ✅ Reject H₀  — statistically significant difference (α=0.05)")
    else:
        print("  ❌ Fail to reject H₀ — no significant difference (α=0.05)")


# ── Main ──────────────────────────────────────────────────
def main():
    print("=" * 55)
    print("  CodeAlpha Task 2 — Exploratory Data Analysis")
    print("=" * 55)

    df, dataset_type = load_data()

    basic_info(df)
    missing_values(df)
    descriptive_stats(df)
    univariate_analysis(df)
    correlation_analysis(df)
    detect_outliers(df)
    categorical_analysis(df)
    hypothesis_test(df, dataset_type)

    print("\n" + "=" * 55)
    print("  ✅ EDA Complete! Charts saved as PNG files.")
    print("=" * 55)


if __name__ == "__main__":
    main()
